#!/usr/bin/env sh

set -e

# This is a fallback value; the actual value should be passed in the environment.
CGO_ENABLED=${CGO_ENABLED:-0}

if test -z "${ROOTDIR}" ; then
	ROOTDIR=$(dirname "$(go env GOMOD)")
	if test -z "${ROOTDIR}" ; then
		ROOTDIR=$(git rev-parse --show-toplevel)
	fi
	ROOTDIR=$(realpath -m "${ROOTDIR}")
fi

. "${ROOTDIR}/.gbt.mk"

if test -z "${GOPATH}" ; then
	GOPATH=$(go env GOPATH)
fi

if test -z "${GOMODCACHE}" ; then
	GOMODCACHE=$(go env GOMODCACHE)
fi

if test -z "${CI}" ; then
	CI=false
fi

if test -z "${GOOS}" ; then
	GOOS=$(go env GOOS)
fi

if test -z "${GOARCH}" ; then
	GOARCH=$(go env GOARCH)
fi

default_docker_sock=/var/run/docker.sock
if test -z "${DOCKER_SOCK}" ; then
  DOCKER_SOCK=${default_docker_sock}
fi

group=$(id -g)
if grep -qe 'docker' /etc/group; then
  group=$(grep -e docker /etc/group | cut -d: -f 3)
fi

tty_flag=""
int_flag=""
if test -t 1 ; then
	tty_flag=--tty
	int_flag=--interactive
fi

exec docker run                                  \
	$tty_flag                                \
	$int_flag                                \
	--rm                                     \
	--user "$(id -u):${group}"               \
	--volume "${ROOTDIR}:${ROOTDIR}"         \
	--volume "${HOME}/.cache:/.cache"        \
	--volume "${GOPATH}:/go"                 \
	--volume "${GOMODCACHE}:/go/pkg/mod"     \
	--volume "${DOCKER_SOCK}:${default_docker_sock}"     \
	--network=host                           \
	--workdir "${PWD}"                       \
	--env CI="${CI}"                         \
	--env CGO_ENABLED="${CGO_ENABLED}"       \
	--env GOOS="${GOOS}"                     \
	--env GOARCH="${GOARCH}"                 \
	"${GBT_IMAGE}"                           \
	"$@"
