name: Build

on:
  pull_request: {}
  push:
    tags:
      - v*

# Needed to create releases.
permissions:
  contents: write

jobs:
  prepare-release:
    name: Conditionally prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh release create "${{ github.ref_name }}"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ prepare-release ]
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Extract k6 version from go.mod
        id: version
        run: |-
          k6version=$(grep -e go.k6.io go.mod | cut -d' ' -f 2)
          echo "Detected k6 version: ${k6version}"
          echo "k6=${k6version}" >> $GITHUB_OUTPUT
      - name: Build with xk6
        run: |-
          docker run --rm -i -u "$(id -u):$(id -g)" -v "${PWD}:/xk6" \
            -e "GOOS=${{ matrix.goos }}" -e "GOARCH=${{ matrix.goarch }}" \
            grafana/xk6 build ${{ steps.version.outputs.k6 }} \
            --output "dist/sm-k6-${{ matrix.goos }}-${{ matrix.goarch }}" \
            --with sm=.
      - name: Upload artifact to release
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh release upload "${{ github.ref_name }}" dist/*
