name: Lint

on:
  pull_request: {}

permissions:
  contents: none
  packages: none

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          persist-credentials: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          only-new-issues: true
          args: --timeout=5m # 1m is not enough, experimentally.
