name: Lint

on:
  pull_request: {}

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@051d91933864810ecd5e2ea2cfd98f6a5bca5347 # v6
        with:
          only-new-issues: true
          args: --timeout=5m # 1m is not enough, experimentally.
