name: Lint

on:
  pull_request: {}

permissions:
  contents: none
  packages: none

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2 DO NOT UPDATE BEYOND THIS VERSION.
        with:
          only-new-issues: true
          version: v1.64.8
          args: --timeout=5m # 1m is not enough, experimentally.
