name: Build

on:
  pull_request: {}
  release:
    types: [published]

permissions:
  contents: none
  packages: none

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    permissions:
      contents: write # Needed to upload assets to releases.
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0

      - name: Extract k6 version from go.mod
        id: version
        run: |-
          k6version=$(grep -e go.k6.io go.mod | cut -d' ' -f 2)
          echo "Detected k6 version: ${k6version}"
          echo "k6=${k6version}" >> $GITHUB_OUTPUT

      - name: Build with xk6
        env:
          K6_VERSION: ${{ steps.version.outputs.k6 }}
        run: |-
          mkdir -p dist
          docker run --rm -i -u "$(id -u):$(id -g)" -v "${PWD}:/xk6" \
            -e "GOOS=${{ matrix.goos }}" -e "GOARCH=${{ matrix.goarch }}" \
            grafana/xk6 build "${K6_VERSION}" \
            --output "dist/sm-k6-${{ matrix.goos }}-${{ matrix.goarch }}" \
            --with github.com/grafana/xk6-sm=. \
            --with github.com/grafana/gsm-api-go-client@f1eb31c337499aab6fe756d4d1dd0f5f16e17826

      - name: Check runner architecture
        id: runner-info
        run: |-
          native="false" runner_arch="${{runner.arch}}" runner_os="${{runner.os}}" goos="${{matrix.goos}}" goarch="${{matrix.goarch}}"
          if [[ "${runner_arch/X/amd}" = "$goarch" ]] && [[ "${runner_os,,}" = "$goos" ]]; then
            native="true"
          fi
          echo "native=$native" >> $GITHUB_OUTPUT

      - name: Test
        # No point in running tests for foreign architectures we cannot run.
        if: steps.runner-info.outputs.native == 'true'
        run: |-
          go test ./...

      - name: Upload artifact to release
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |-
          gh release upload "${GITHUB_REF_NAME}" dist/* --clobber
