name: Build

on:
  pull_request: {}
  release:
    types: [published]

# Needed to upload assets to releases.
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
      - name: Extract k6 version from go.mod
        id: version
        run: |-
          k6version=$(grep -e go.k6.io go.mod | cut -d' ' -f 2)
          echo "Detected k6 version: ${k6version}"
          echo "k6=${k6version}" >> $GITHUB_OUTPUT
      - name: Build with xk6
        run: |-
          mkdir -p dist
          docker run --rm -i -u "$(id -u):$(id -g)" -v "${PWD}:/xk6" \
            -e "GOOS=${{ matrix.goos }}" -e "GOARCH=${{ matrix.goarch }}" \
            grafana/xk6 build ${{ steps.version.outputs.k6 }} \
            --output "dist/sm-k6-${{ matrix.goos }}-${{ matrix.goarch }}" \
            --replace golang.org/x/crypto=golang.org/x/crypto@v0.33.0 \
            --replace golang.org/x/net=golang.org/x/net@v0.33.0 \
            --with github.com/grafana/xk6-sm=.

      - name: Upload artifact to release
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh release upload "${{ github.ref_name }}" dist/* --clobber
