name: Validate renovate config
on:
  pull_request:
    paths:
      - "**renovate*.*"
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Validate renovate config
        run: |-
          # Renovate updates the line below. Please keep its formatting as it is.
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:38.142.6@sha256:51f47d953e6c8ea46ba7acffcfc9151e7be9f27a7e0bc828388ff1e5207de1f3
          docker run -i --rm -v $(realpath .):/repo -w /repo --entrypoint renovate-config-validator "$RENOVATE_IMAGE" --strict
