name: Self-hosted Renovate

on:
  schedule:
    - cron: "29 */4 * * *"
  workflow_dispatch:

jobs:
  renovate:
    permissions:
      # Needed for logging into vault.
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Self-hosted renovate
        uses: grafana/sm-renovate/actions/renovate@main
        with:
          dry-run: "${{ github.event_name == 'pull_request' }}"
          use-current-branch: "${{ github.event_name == 'pull_request' }}"
