name: Validate renovate config
on:
  pull_request:
    paths:
      - "**renovate*.*"
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Validate renovate config
        run: |-
          # Renovate updates the line below. Please keep its formatting as it is.
          export RENOVATE_IMAGE=ghcr.io/renovatebot/renovate:39.31.0@sha256:ea2b64778453a944cc982b6bb42b7581a7d526cab1bb2fa09a13cacd5525c9fe
          docker run -i --rm -v $(realpath .):/repo -w /repo --entrypoint renovate-config-validator "$RENOVATE_IMAGE" --strict
